services:
  postgres:
    image: postgres:13.3
    container_name: userAPI
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /Users/ksenia/userapi/docker/redis/redis.conf:/userapi/docker/redis/redis.conf
        - redis:/etc/redis
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16