port: "8080"
signingKey: "djf2kj9(9e9)#j"

db:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "qwerty"
  dbname: "users"
  sslmode: "disable"
redis_db:
  host: "localhost"
  port: "6379"
  exp_time_seconds: "60"